### PR TITLE
Fix bot menu color

### PR DESCRIPTION
**Pull request by kirizdev**
Before: 
image

After: 
image

### CODE REVIEW

**Comment by maximilionus** [comment]
I noticed this issue several days ago, but sadly had no time to look into it. Thank you very much for fixing it. I'm going to review the changes asap.

**Comment by kirizdev** [comment]
Great! Not really sure about the color. I took the color from the message placeholder, but it looks a little pale, #ffffff is too bright and too noticeable for such a small element

**Review by maximilionus — APPROVED** [review]
Color choice is great. I don't think this button should stand out from all the other elements in this group.

**Comment by maximilionus** [comment]
Already applied the changes to cloud version. Thank you for this contribution! ❤️

**Pull request merged**
